apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: nedim-spring-boot-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: nedim-spring-boot-demo
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17.*"
  # source:
  #   git:
  #     url: https://git.example.com/my-repo
  #     ref:
  #       branch: main
